// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { env } from './src/lib/schema/env/server';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'src/lib/schema/prisma/schema.prisma',
  migrations: {
    path: 'src/lib/schema/prisma/migrations',
  },
  datasource: {
    url: env['DATABASE_URL'],
  },
});
