// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';

import { env } from './src/lib/schema/env/server';

export default defineConfig({
  schema: 'src/lib/schema/prisma/schema.prisma',
  migrations: {
    path: 'src/lib/schema/prisma/migrations',
    seed: 'tsx src/db/seed.ts',
  },
  datasource: {
    url: env.DATABASE_URL,
  },
});
