# app
FROM mcr.microsoft.com/devcontainers/base:ubuntu

#RUN apt-get update
#RUN export DEBIAN_FRONTEND=noninteractive
#RUN apt-get -y install --no-install-recommends git curl build-essential wget jq
#RUN apt-get -y install python3 python3-pip

USER vscode
